source/QuestionBank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question/', include('questions.urls')),
    path('question/', include('questions.api_urls')),
    path('accounts/', include('accounts.urls')),
    path('docs/', include('rest_framework_docs.urls')),
    path('', TemplateView.as_view(template_name='index.html'
                                 ), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth import views as authviews
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', authviews.LoginView.as_view(), name='login'),
    path('logout/', authviews.LogoutView.as_view(), name='logout'),
]

source/questions/urls.py
"""
Web URLS for question app.
"""

from django.urls import path

from . import views

app_name = 'questions'

urlpatterns = [
    path('paper/<int:pk>',
         views.QuestionPaperDetail.as_view()),
    path('upload',
         views.UploadQuestions.as_view(),
         name='upload'),
    path('paper/details/<int:pk>',
         views.QuestionPaperDetail.as_view(),
         name='question_paper_details'),
    path('paper/<int:pk>/add',
         views.AddQuestionToPaper.as_view(),
         name='add_question_to_paper'),
    path('search/<int:pk>',
         views.SearchView.as_view(),
         name='search_view'),
    path('set/<int:pk>/<passcode>',
         views.SetDetail.as_view(),
         name='set_detail'),
    path('set/',
         views.QuestionSetCreate.as_view(),
         name='set_create'),
    path('sets/',
         views.QuestionSetList.as_view(),
         name='set_list'),
    path('<int:pk>/delete',
         views.QuestionDelete.as_view(),
         name='delete_q'),
]

source/questions/models.py
"""
Models for the question app.
"""
from django.conf import settings
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    """
    Model for storing tag and related info.

    This model stores information related to tags.
    Each node, except the root node has a parent associated with it.
    The immediate children of the root node are major subject areas such as
    Science, Humanities, etc.
    """
    name = models.CharField(max_length=30)
    parent = models.ForeignKey('self',
                               related_name='children',
                               on_delete=models.SET_NULL,
                               null=True, blank=True)

    def __str__(self):
        return self.name


class QuestionPaper(models.Model):
    """
    Model for storing Question paper file and related info.

    On upload, the question paper is parsed using fitz and the raw text thus
    extracted is stored with the question paper. The uploader can go through
    the raw text and select certain questions from it.
    """
    file = models.FileField(upload_to='media/papers',
                            blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.SET_NULL,
                              null=True, blank=True)
    tag_str = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        """Returns absolute url of the question paper."""
        return reverse('questions:question_paper_details', args=[self.id])


class Question(models.Model):
    """
    Model for storing each question and related info.

    This stores information related to a question, such as the question text,
    tags related to it, it's owner, and also it's difficulty, which an integer,
    which is an indicator of how much marks should be awarded for the given
    question.
    """
    text = models.TextField(blank=True, null=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                null=True, blank=True)
    notes = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    tags_frozen = models.BooleanField(default=False)
    source = models.ForeignKey(QuestionPaper,
                               blank=True, null=True,
                               related_name='questions',
                               on_delete=models.SET_NULL)
    difficulty = models.PositiveIntegerField(blank=True, null=True,
                                             help_text="Marks will be allotted"
                                             "on the basis of this.")
    similar_to = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.text[:100]


class QuestionSet(models.Model):
    """QuestionSet for setting questions."""

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.SET_NULL,
                              null=True, blank=True)
    name = models.CharField(max_length=30, blank=True, null=True,
                            help_text="Enter a name of your choice")
    passcode = models.CharField(max_length=5, blank=True, null=True,
                                help_text="Use this if you want this to be accesssible to only people who have this passcode.")
    start_time = models.DateTimeField(blank=True, null=True,
                                      help_text="Use this if you want this to be accessible only after a certain time.")
    end_time = models.DateTimeField(blank=True, null=True,
                                    help_text="Use this if you want this set to be accessible only until a certain time.")
    questions = models.ManyToManyField(Question)
    total_marks = models.PositiveIntegerField(default=100)

    def get_absolute_url(self):
        """Returns canonical url or the Question set."""
        return reverse('questions:search_view', args=[self.id])

source/questions/forms.py
from django.forms import ModelForm
from .models import QuestionPaper

class QuestionForm(ModelForm):
    class Meta:
        model = QuestionPaper
        fields = ('file',)

source/questions/views.py
"""
Web views for the Question app.
"""
import fitz
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView

from .forms import QuestionForm
from .models import Question, QuestionPaper, QuestionSet, Tag


class UploadQuestions(LoginRequiredMixin, View):
    """Upload a question paper, and then redirect the user to the page
    associated with the question paper."""
    login_url = '/accounts/login'

    def get(self, request):
        """Handles get method; show user a form to upload papers."""
        form = QuestionForm()
        context = {
            'form': form,
            'papers': QuestionPaper.objects.all(),
        }
        return render(request, 'questions/upload.html', context)

    def post(self, request):
        """Handles post method.

        Redirect user to paper detail page if upload successful.

        Re-render the same page with errors if not."""
        form = QuestionForm(request.POST, request.FILES)
        qpaper = form.save()
        try:
            doc = fitz.open(qpaper.file.path)
            text = ""
            for page in doc.pages():
                text += page.getText()
            qpaper.text = text
            qpaper.save()
            return redirect(qpaper.get_absolute_url())
        except Exception as err:
            form.add_error(None, "Couldn't parse file." + str(err))
            raise
        context = {
            'form': form,
            'papers': QuestionPaper.objects.all(),
        }
        return render(request, 'questions/upload.html', context)


class QuestionPaperDetail(DetailView): # pylint: disable=too-many-ancestors
    """
    Return details for a question paper along with root tag.

    'root' is augmented data for parsing the tag tree.
    """
    model = QuestionPaper

    def get_context_data(self, **kwargs):
        context = super(QuestionPaperDetail, self).get_context_data(**kwargs)
        root = Tag.objects.get(name='root')
        context['root'] = root
        return context


class AddQuestionToPaper(View):
    """Adds a question to a question paper."""

    def post(self, request, pk):
        """Handle post method.

        Add a question to the database, and assign a paper to it.
        """
        text = request.POST['text']
        difficulty = request.POST.get('difficulty')
        tags = request.POST.get('tags')
        paper = QuestionPaper.objects.get(pk=pk)
        paper.tag_str = tags
        paper.save()
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        question = Question.objects.create(
            text=text, source=paper, creator=user)
        tags = [i.strip() for i in tags.split(',') if i.strip()]
        for tag in tags:
            tag_obj = Tag.objects.get(name=tag)
            question.tags.add(tag_obj)
        if difficulty:
            question.difficulty = difficulty
        question.save()

        return redirect(paper.get_absolute_url())


class SearchView(LoginRequiredMixin, View):
    """
    View for a question set.

    User can search for questions and add them into the set here.
    """
    def get(self, request, pk):
        """Handles get method."""
        qset, _ = QuestionSet.objects.get_or_create(pk=pk, defaults={
            'owner': self.request.user if (
                self.request.user.is_authenticated
            ) else None,
            'passcode': get_random_string(5).upper(),
        })
        root = Tag.objects.get(name='root')
        context = {
            'qset': qset,
            'root': root,
        }
        if qset.owner == self.request.user:
            return render(request, 'questions/index.html', context)
        # return redirect(

class SetDetail(DetailView):
    """Get the details of the set."""
    model = QuestionSet

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, id=self.kwargs['pk'])
        print(obj)
        print(obj.passcode)
        if obj.passcode is not None:
            return get_object_or_404(self.model, id=self.kwargs['pk'], passcode=self.kwargs['passcode'])
        else:
            return obj

    # def get_context_data(self, **kwargs):
        # context = super(QuestionPaperDetail, self).get_context_data(**kwargs)
        # root = Tag.objects.get(name='root')
        # context['root'] = root
        # return context




class QuestionSetCreate(LoginRequiredMixin, CreateView): # pylint: disable=too-many-ancestors
    """
    Allow users to init question set creation.
    """
    model = QuestionSet
    fields = ['name', 'passcode', 'start_time', 'end_time']

    def form_valid(self, form):
        """Override form validation; add owner of set."""

        form.instance.owner = self.request.user
        return super().form_valid(form)

class QuestionSetList(ListView): # pylint: disable=too-many-ancestors
    """
    Return list of all sets created by the user.
    """
    model = QuestionSet

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)

class QuestionDelete(DeleteView): # pylint: disable=too-many-ancestors
    """
    Deletes a question and redirects to home.
    """
    model = Question
    success_url = reverse_lazy('home')

source/templates/questions/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>QMark | {% block title %}{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/third-party/bootstrap-3.4.0.min.css' %}"/>
    <script src="{% static 'js/third-party/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/third-party/bootstrap-3.4.0.min.js' %}"></script>
    <script src="{% static 'js/third-party/axios.min.js' %}"></script>
    <script src="{% static 'js/third-party/lodash.min.js' %}"></script>
    <script src="{% static 'js/third-party/vue.js' %}"></script>


    <!--<link href="css/mdb.min.css" rel="stylesheet">-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    {% block styles %}

    {% endblock %}
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            QMark
          </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            {% comment %}<li class="active"><a href="#">Home</a></li>{% endcomment %}
            <li><a href="/question/upload">Upload</a></li>
            <li><a href="{% url 'questions:set_list' %}">My Sets</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>

                {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}">
                  <span class="glyphicon glyphicon-user"></span> {{ request.user }} [<b>Logout</b>]
                </a>
                {% else %}
              <a href="{% url 'accounts:login' %}">
                <span class="glyphicon glyphicon-log-in"></span> Login
              </a>
                {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      <hr width=100%>
      <h4 style="background-color: #b7521e; text-align:center; margin:0;">
        &copy;TTFKAH, 2019
      </h4>
      {% block scripts %}
      {% endblock %}
  </body>
</html>

source/templates/questions/index.html
{% extends 'questions/base.html' %}
{% block title %}
Question Set {{ qset.id }}
{% endblock %}

{% block styles %}
<style type="text/css" media="screen">
.add-set {
  float:right;
  margin-top: -40px;
}

.tags {
  text-align: right;
    margin-right: 10px;
}
.tags div {
  float: right;
  border: 1px solid gray;
    padding: 0;
      text-align: center;
}

.nocare {
  background: white;
}

.whitelisted {
  background: lightgreen;
}

.blacklisted {
  background: pink;
}

.hider {
  font-size: 10px;
  float: right;
}

div.hid {
  display: none;
}

#taglist .nocare:hover {
  background: rgba(0,0,0,0.06);
}

</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div id="taglist" class="col-sm-2">
    {% include "questions/tag.html" with tag_list=root.children.all %}
  </div>

  <div id='app' class="col-sm-5">
    {% verbatim %}

    <form class="form-group">
      <input class="form-control" placeholder="Search for questions." v-model="text">
      <input class="form-control" placeholder="Add tags to search" id="whitelist" v-model="whitelist" readonly=True>
      <input class="form-control" placeholder="Blacklist tags to not search in" id="blacklist" v-model="blacklist" readonly=True>
    </form>
    <div id="status" class="name">
      {{ status }}
    </div>
    <div v-for="(question, resKey) in questions" class="question">
      <div class="text">
        <pre>{{ question.text }} 
        </pre>
      </div>
      <button class="btn btn-info add-set" @click="addToSet(question.id)">Add</button>
      <div class="marks">
        {{ question.difficulty }}
      </div>
    </div>
    {% endverbatim %}
  </div>

  <div class="col-sm-5">
    <div id="show">
      {% verbatim %}
      Question set {{ qset.id }} currently has {{ qset.questions.length }} question(s).
      <div class="question" v-for="question in qset.questions">
        <br>
        <br>
        {{ question.text }}
      </div>
      {% endverbatim %}
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'js/main.js' %}"></script>
<script>
  let id = {{ qset.id }};

  $('.hider').click(function(e){
    e.stopPropagation()
    $(this).parent().children().toggleClass('hid')
    this.innerHTML = this.innerHTML == '(show)' ? '(hide)' : '(show)'
  })

  $('#taglist div').click(function(e){
    tag = this.getAttribute('tagName');
    wl = $('#whitelist')
    bl = $('#blacklist')
    e.stopPropagation()
    if (this.className == 'nocare')
    {
      {% comment %}alert('nocare to wl'){% endcomment %}
      $(this).toggleClass('nocare')
      $(this).toggleClass('whitelisted')
      curr = wl.val()
      if (curr.length>0)
        curr += ', '
      curr += tag
      curr = curr.replace(", ,", ",")
      wl.val(curr)
    }
    else if (this.className == 'whitelisted'){
      $(this).toggleClass('blacklisted')
      $(this).toggleClass('whitelisted')
      curr = wl.val()
      curr = curr.replace(tag, "");
      curr = curr.replace(", ,", ",");
      wl.val(curr)

      curr = bl.val()
      if (curr.length>0){
        curr += ', '
      }
      bl.val(curr + tag);
    }
    else if (this.className == 'blacklisted'){
      $(this).toggleClass('blacklisted')
      $(this).toggleClass('nocare')
      curr = bl.val()
      curr = curr.replace(tag, "");
      curr = curr.replace(", ,", ",")
      bl.val(curr)
    }
    else {
      alert("something went wrong")
    }
    app.blacklist = bl.val()
    app.whitelist = wl.val()
  });

</script>
{% endblock %}

source/templates/questions/question_confirm_delete.html
{% extends 'questions/base.html' %}
{% block title %}
Confirm Deletion
{% endblock %}
{% block content %}
<div class="container">
<h2>
  Are you sure you want to delete this question?
</h2>
<form method = POST >
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-danger"> Delete </button>
</form >
</div>
{% endblock %}

source/templates/questions/questionpaper_detail.html
{% extends 'questions/base.html' %}
{% block title %}
Question Paper
{% endblock %}
{% block styles %}
<style type="text/css" media="screen">
html, body {
  height: 99.5%;
}
main {
  height: 95%}

#left {
  overflow: scroll;
  height: 100%;
}

#top {
  margin-top: 10px;
}

#right {
  height: 100%;
}
#right #bottom {
  overflow: scroll;
  max-height: 75%;
  overflow: -moz-scrollbars-none;
  scrollbar-width: none;
}
#selector {
  z-index: 50;
  position: fixed;
  top: 50%;
  right: 58%;
  border-radius: 50%;
  padding: 8px;
  background: rgba(76, 175, 80, 0.8)
}

.hider {
  font-size: 10px;
  float: right;
}

div.hid {
  display: none;
}

div.nocare {
  background: white;
}

div.selected {
  background: lightgreen;
}

#taglist .nocare:hover {
  background: rgba(0,0,0,0.06);
}
.question {
  background: rgb(230,230,230);
}
.tags {
  margin-top: -10px;
}
.tag{
  padding: 1px 1px;
  text-align: center;
  float:right;
  border: 1px dashed gray;
  margin-right: 5px;
}

</style>
{% endblock %}
{% block content %}
<button id="selector" class="btn" onclick=selection()>
  <img src="https://icons-for-free.com/iconfiles/png/512/keyboard+arrow+right+24px-131985225827089442.png" height=30 width=30>
</button>
<div class="col-sm-5 col-md-5" id="left">
  {{ object.text | linebreaks | safe }}
</div>

<div class="col-sm-5 col-md-5" id="right">
  <div id=top>
    <form method="POST" action="/question/paper/{{ object.id }}/add">
      {% csrf_token %}
      <textarea id="question_sel" cols=60 rows=7 name="text"/>
      </textarea>
      <label> Tags: <input id="taglist" type="text" name="tags"></label>
      <label> Difficulty: <input id="difficulty" type="text" name="difficulty"></label>
      <br>
      <button type="submit" class="btn btn-success" id="add-button">Add</button>
    </form>
  </div>
  <div id=bottom>
    <b>{{ object.questions.count }} questions{{ questions | pluralize}}</b> extracted.

    <br>
    {% for question in object.questions.all %}
    <div class="question">
      {{ question.text | linebreaks | safe }}
    </div>
    <div class="tags row">
      {% for tag in question.tags.all %}
      <div class="tag col-sm-2">
        {{ tag }}
      </div>
      {% endfor %}
      <a href="{% url 'questions:delete_q'  question.id %}">
        <div class="btn btn-danger tag delete col-sm-2">
          Delete
        </div>
      </a>
      {% if question.difficulty %}
      <div class="btn btn-info tag col-sm-1">
        {{ question.difficulty }}
      </div>
      {% endif %}
    </div>
    <br>
    {% endfor %}
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>

<div id="taglist" class="col-sm-2">
  {% include "questions/tag.html" with tag_list=root.children.all %}
</div>
{% endblock %}

{% block scripts %}
<script>

  tl = $('#taglist')
  $(document).ready(function(){
    var str = {% if object.tag_str %} "{{ object.tag_str }}" {% else %} "" {% endif %}
    tl.val(str)
    str.split(",").map(function(item){
      item = item.trim()
      if(item.length){
        $('div[tagName="'+item+'"]').addClass('selected')
        $('div[tagName="'+item+'"]').removeClass('nocare')
      }
      return null
    })

  })



  $('.hider').click(function(e){
    e.stopPropagation()
    $(this).parent().children().toggleClass('hid')
    this.innerHTML = this.innerHTML == '(show)' ? '(hide)' : '(show)'
  })

  function selection(){
    p = window.getSelection().toString()
    if(p) {
      document.getElementById('question_sel').value = p
    }
    else {
      document.getElementById('question_sel').value = ""
    }
  }


  function removeSel(ell){
    tag = ell.getAttribute('tagName')
    $(ell).removeClass('selected')
    $(ell).addClass('nocare')
    curr = tl.val()
    curr = curr.replace(tag, "");
    curr = curr.replace(", ,", ",");
    tl.val(curr)
    $(ell).children('.selected').each(function(i, val) {
      removeSel(val)
    })
  }

  $('#taglist div').click(function(e){
    tag = this.getAttribute('tagName');
    if (this.className == 'nocare')
    {
      $(this).removeClass('nocare')
      $(this).addClass('selected')
      curr = tl.val()
      if (curr.length>0)
        curr += ', '
      curr += tag
      curr = curr.replace(", ,", ",")
      tl.val(curr)
      if ($(this).parent().hasClass('selected'))
        e.stopPropagation()
    }
    else if (this.className == 'selected'){
      e.stopPropagation()
      removeSel(this)
    }
    else {
      alert("something went wrong")
    }
  });
</script>
{% endblock %}

source/templates/questions/questionset_detail.html
{% extends 'questions/base.html' %}
{% block title %}
Question Set {{ qset.id }}
{% endblock %}

{% block styles %}
<style>
h1 {
  color: gray;
}
h1 span {
  color: black;
}
.question {
  background: rgba(0, 0, 0, .15);
  padding: 10px;
  margin: 10px;
}
.tags {
  margin-top: -10px;
  margin-left: 10px;
}
.tags div{
  border: 1px solid gray;
  padding: 0;
  text-align: center;
}
.question .marks {
  border: 1px dashed black;
    padding: 6px 0;
  text-align: center;
}

</style>
{% endblock %}
{% block content %}
<div class="container">
  <h1>
    Question Set
    <span>
      {% if object.name %}
      {{ object.name }}
      {% else %}
      [Unnamed]
      {% endif %}
    </span>
  </h1>
  {% for question in object.questions.all %}
  <div class='question row'>
    <div class="text col-sm-11">
      {{ question.text | linebreaks }}
    </div>
    {% if question.difficult %}
    <div class="marks col-sm-1">
      {{ question.difficulty }}
    </div>
    {% else %}
    <div class="marks col-sm-1">
      1
    </div>
    {% endif %}
  </div>
  <div class='tags row'>
    {% for tag in question.tags.all %}
    <div class='col-sm-1'>
      {{ tag }}
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

source/templates/questions/questionset_form.html
{% extends 'questions/base.html' %}
{% block title %}
Create Question Set
{% endblock %}

{% block styles %}
<style type="text/css" media="screen">
</style>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Create new question set</h1>
<form method="POST">
  {% load crispy_forms_tags %}
  {%csrf_token%}
  {{ form|crispy }}
  <button class="btn btn-primary">Create</button>
</form>
</div>

{% endblock %}

{% block scripts %}
 <script>
   $(document).ready(function() {
    $(".datetimeinput").attr("type", "date")
});
 </script>
 {% endblock %}

source/templates/questions/questionset_list.html
{% extends 'questions/base.html' %}

{% block title %}
My Sets
{% endblock %}
{% block content %}
<div class="container">
  {% for set in object_list %}
  <div class="row">
    <div class="col-sm-2">
      <a href="{{ set.get_absolute_url }}">
        {% if set.name %}
        {{ set.name }}
        {% else %}
        Unnamed set
        {% endif %}
      </a>
    </div>
    <div class="col-sm-2">
      contains <b>{{ set.questions.all.count }}</b> question{{ set.questions.all|pluralize }}
    </div>
    <div class="col-sm-2">
      <a href="{% url 'questions:set_detail' set.id  set.passcode %}">Public link</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

source/templates/questions/tag.html
{% for tag in tag_list %}
<div style="padding-left: 8px;" tagName="{{ tag.name }}" class="nocare">
  {{ tag.name }}
  {% if tag.children.all %}
    <span class="hider">(hide)</span>
    {% include "questions/tag.html" with tag_list=tag.children.all %}
  {% endif %}
  </div>
{% endfor %}

source/templates/questions/upload.html
{% extends 'questions/base.html' %}
{% block styles %}
<style>
.paper_text{
    margin-left: 50px;
    margin-bottom: 20px;
}
</style>
{% endblock %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_file">File:</label><input type="file" name="file" id="id_file" required=True>
        <br>
        <button type="submit">Submit</button>
    </form>

    Before uploading, make sure you're not uploading one of the already available papers:
    <br>
    <br>

    {% for paper in papers %}
    {% if paper.file %}
    <a href="{{ paper.get_absolute_url }}">{{ paper.file.name }}</a>
    &nbsp; &nbsp; &nbsp; &nbsp;
    <small>[<a href="{{ paper.file.url }}">Get file</a>]</small>
    {% endif %}
    <div class="paper_text">{{ paper.text | truncatewords:50 }}
    </div>
    {% endfor %}
</div>
{% endblock %}